---
    - name: Create EME base directory
      file:
       path: '{{ eme_base_dir }}'
       state: directory
       owner: '{{ ai_user }}'
       group: '{{ ai_group }}'
       mode: 0755

    - name: Creating repository
     become: yes
     become_user: '{{ ai_user }}'
     shell: |
        cd /home/{{ ai_user }}
        source /home/{{ ai_user }}/.bashrc
        export AB_HOME={{ ab_home_path }}
        export AB_APPLICATION_HUB={{ application_hub_path }}
        export PATH=$PATH:$AB_HOME/bin
        export AB_AIR_ROOT={{ eme_base_dir }}/{{ eme_name }}
        air repository create

